import { useMemo, useState, type FormEvent } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../../lib/supabase';
import type { Product } from '../../lib/database.types';
import { Package, Plus, X, Pencil } from 'lucide-react';
import { useDialog } from '../../lib/useDialog';

type ProductRow = Product;

type TypeFilter   = 'all' | 'durable' | 'consumable';
type ActiveFilter = 'active' | 'all' | 'inactive';

/**
 * /dashboard/admin/products
 *
 * The fabricable + distributable catalogue. Admin-only writes (RLS).
 *
 * SKUs are auto-generated by a BEFORE INSERT trigger on the products table
 * (see 20260601000008_auto_generate_sku.sql) — we don't expose a SKU input
 * on create. On edit we show the generated SKU but keep it read-only.
 *
 * Data layer: TanStack Query. Cache key ['products'] is invalidated by
 * mutations below and from anywhere else (e.g. AdminDistribute create) so
 * the catalogue stays fresh without manual reload calls.
 */
export function AdminProducts() {
  const qc = useQueryClient();

  const [typeFilter,   setTypeFilter]   = useState<TypeFilter>('all');
  const [activeFilter, setActiveFilter] = useState<ActiveFilter>('active');

  const [editing,  setEditing]  = useState<ProductRow | null>(null);
  const [creating, setCreating] = useState(false);

  // === Shared, cached products query ===
  // Multiple components (Distribute, Orders forms, this page) all key on
  // ['products'] so they share one fetch + one cache entry. Background
  // refetch on focus keeps it fresh.
  const {
    data:    products,
    error:   queryErr,
  } = useQuery({
    queryKey: ['products'],
    queryFn: async (): Promise<ProductRow[]> => {
      const { data, error } = await supabase
        .from('products')
        .select('*')
        .order('created_at', { ascending: false });
      if (error) throw new Error(error.message);
      return data as ProductRow[];
    },
  });

  // === Toggle active mutation ===
  // Optimistic update: flip the row's is_active locally before the network
  // round-trip so the badge updates instantly. Roll back on failure.
  const toggleActive = useMutation({
    mutationFn: async (input: { id: string; current: boolean }) => {
      const { error } = await supabase
        .from('products')
        .update({ is_active: !input.current })
        .eq('id', input.id);
      if (error) throw new Error(error.message);
    },
    onMutate: async ({ id, current }) => {
      await qc.cancelQueries({ queryKey: ['products'] });
      const previous = qc.getQueryData<ProductRow[]>(['products']);
      qc.setQueryData<ProductRow[]>(['products'], (rows) =>
        rows?.map((r) => (r.id === id ? { ...r, is_active: !current } : r)),
      );
      return { previous };
    },
    onError: (_e, _v, ctx) => {
      if (ctx?.previous) qc.setQueryData(['products'], ctx.previous);
    },
    onSettled: () => qc.invalidateQueries({ queryKey: ['products'] }),
  });

  const err = queryErr?.message ?? toggleActive.error?.message ?? null;

  const filtered = useMemo(() => {
    if (!products) return null;
    return products.filter((p) => {
      if (typeFilter === 'durable'    && !p.is_durable) return false;
      if (typeFilter === 'consumable' &&  p.is_durable) return false;
      if (activeFilter === 'active'   && !p.is_active)  return false;
      if (activeFilter === 'inactive' &&  p.is_active)  return false;
      return true;
    });
  }, [products, typeFilter, activeFilter]);

  const counts = useMemo(() => ({
    total:      products?.length ?? 0,
    durable:    products?.filter((p) => p.is_durable).length ?? 0,
    consumable: products?.filter((p) => !p.is_durable).length ?? 0,
    inactive:   products?.filter((p) => !p.is_active).length ?? 0,
  }), [products]);

  const onDeactivate = (id: string, current: boolean) => {
    toggleActive.mutate({ id, current });
  };

  return (
    <div className="px-4 sm:px-6 lg:px-10 py-8 space-y-6">
      <div className="flex items-end justify-between gap-4 flex-wrap">
        <div>
          <p className="text-xs uppercase tracking-wider text-gray-500 mb-1">Admin</p>
          <h1>Products</h1>
          <p className="text-sm text-gray-600 mt-1 max-w-2xl">
            The catalogue every school orders from. SKUs are generated automatically when you
            add a product — no need to invent one.
          </p>
        </div>
        <button
          onClick={() => { setCreating(true); setEditing(null); }}
          className="btn-primary w-full sm:w-auto justify-center"
        >
          <Plus className="h-4 w-4 mr-1.5" aria-hidden="true" />
          Add product
        </button>
      </div>

      {err && (
        <div role="alert" className="text-sm text-red-700 bg-red-50 border border-red-200 rounded-md px-3 py-2">
          {err}
        </div>
      )}

      {/* Filter pills */}
      <div className="flex flex-wrap gap-3 items-center">
        <div className="flex flex-wrap gap-1.5">
          <Pill active={typeFilter === 'all'}        onClick={() => setTypeFilter('all')}>
            All <span className="ml-1.5 text-gray-400">{counts.total}</span>
          </Pill>
          <Pill active={typeFilter === 'durable'}    onClick={() => setTypeFilter('durable')}>
            Durables <span className="ml-1.5 text-gray-400">{counts.durable}</span>
          </Pill>
          <Pill active={typeFilter === 'consumable'} onClick={() => setTypeFilter('consumable')}>
            Consumables <span className="ml-1.5 text-gray-400">{counts.consumable}</span>
          </Pill>
        </div>
        <span className="w-px h-5 bg-warm-200" />
        <div className="flex flex-wrap gap-1.5">
          <Pill active={activeFilter === 'active'}   onClick={() => setActiveFilter('active')}>
            Active only
          </Pill>
          <Pill active={activeFilter === 'all'}      onClick={() => setActiveFilter('all')}>
            All states
          </Pill>
          <Pill active={activeFilter === 'inactive'} onClick={() => setActiveFilter('inactive')}>
            Inactive <span className="ml-1.5 text-gray-400">{counts.inactive}</span>
          </Pill>
        </div>
      </div>

      {/* Create / Edit form */}
      {(creating || editing) && (
        <ProductForm
          initial={editing}
          onClose={() => { setCreating(false); setEditing(null); }}
          onSaved={() => {
            setCreating(false);
            setEditing(null);
            void qc.invalidateQueries({ queryKey: ['products'] });
          }}
        />
      )}

      {/* Table */}
      <section>
        <div className="flex items-center gap-2 mb-3">
          <Package className="h-4 w-4 text-teal-700" aria-hidden="true" />
          <h2 className="m-0">Catalogue</h2>
          <span className="text-xs text-gray-500">{filtered?.length ?? 0}</span>
        </div>
        <div className="card overflow-x-auto">
          <table className="data-table" aria-label="Products catalogue">
            <thead>
              <tr>
                <th scope="col">SKU</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Category</th>
                <th scope="col">State</th>
                <th scope="col" className="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {!filtered && (
                <tr><td role="status" colSpan={6} className="text-center text-gray-500 py-8">Loading…</td></tr>
              )}
              {filtered && filtered.length === 0 && (
                <tr>
                  <td colSpan={6} className="text-center text-gray-500 py-8">
                    No products match this filter.
                  </td>
                </tr>
              )}
              {filtered?.map((p) => (
                <tr key={p.id} className={p.is_active ? '' : 'opacity-60'}>
                  <td className="font-mono text-xs">{p.sku ?? '—'}</td>
                  <td className="whitespace-normal">
                    <div className="font-medium text-gray-900">{p.name}</div>
                    {p.description && (
                      <div className="text-xs text-gray-500 line-clamp-2 max-w-md">
                        {p.description}
                      </div>
                    )}
                  </td>
                  <td>
                    {p.is_durable
                      ? <span className="badge-teal">durable</span>
                      : <span className="badge-amber">consumable</span>}
                  </td>
                  <td className="text-sm text-gray-700">{p.category ?? '—'}</td>
                  <td>
                    {p.is_active
                      ? <span className="badge-green">active</span>
                      : <span className="badge-gray">inactive</span>}
                  </td>
                  <td className="text-right whitespace-nowrap">
                    <button
                      onClick={() => { setEditing(p); setCreating(false); }}
                      className="text-xs text-teal-700 hover:underline inline-flex items-center"
                    >
                      <Pencil className="h-3 w-3 mr-1" aria-hidden="true" />
                      Edit
                    </button>
                    <button
                      onClick={() => onDeactivate(p.id, p.is_active)}
                      className="text-xs text-gray-500 hover:text-gray-900 ml-3"
                    >
                      {p.is_active ? 'Deactivate' : 'Reactivate'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function Pill({
  active, onClick, children,
}: { active: boolean; onClick: () => void; children: React.ReactNode }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`px-3 py-1 rounded-full text-xs border transition-colors ${
        active
          ? 'bg-gray-900 text-white border-gray-900'
          : 'bg-white text-gray-700 border-warm-200 hover:bg-warm-100'
      }`}
    >
      {children}
    </button>
  );
}

function ProductForm({
  initial,
  onClose,
  onSaved,
}: {
  initial: ProductRow | null;
  onClose: () => void;
  onSaved: () => void;
}) {
  const isEdit = !!initial;
  const [name,        setName]        = useState(initial?.name ?? '');
  const [description, setDescription] = useState(initial?.description ?? '');
  const [category,    setCategory]    = useState(initial?.category ?? '');
  const [isDurable,   setIsDurable]   = useState<boolean>(initial?.is_durable ?? true);
  const [isActive,    setIsActive]    = useState<boolean>(initial?.is_active ?? true);
  const [saving,      setSaving]      = useState(false);
  const [err,         setErr]         = useState<string | null>(null);

  const dialogRef = useDialog<HTMLDivElement>({ open: true, onClose, trapFocus: false });

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    setSaving(true);
    setErr(null);

    // v1: all products come from ChipuRobo; designed_by_school_id stays null.
    const payload = {
      name:        name.trim(),
      description: description.trim() || null,
      category:    category.trim() || null,
      is_durable:  isDurable,
      is_active:   isActive,
      // sku omitted on insert; trigger fills it. omitted on update so it
      // never changes once generated.
    };

    const { error } = isEdit
      ? await supabase.from('products').update(payload).eq('id', initial!.id)
      : await supabase.from('products').insert(payload);

    setSaving(false);
    if (error) setErr(error.message);
    else onSaved();
  };

  return (
    <div ref={dialogRef} role="region" aria-labelledby="product-form-heading" className="card p-5">
      <div className="flex items-center justify-between mb-4">
        <h2 className="m-0" id="product-form-heading">{isEdit ? `Edit ${initial?.name}` : 'New product'}</h2>
        <button onClick={onClose} className="p-1 text-gray-500 hover:text-gray-900" aria-label="Close product form">
          <X className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>

      <form onSubmit={onSubmit} aria-labelledby="product-form-heading" className="grid sm:grid-cols-2 gap-4">
        {isEdit && (
          <div className="sm:col-span-2">
            <label className="field-label" htmlFor="product-sku">SKU (auto-generated, read-only)</label>
            <input
              id="product-sku"
              type="text"
              className="field-input font-mono bg-warm-100 text-gray-600 cursor-not-allowed"
              value={initial?.sku ?? ''}
              readOnly
            />
          </div>
        )}

        <div className="sm:col-span-2">
          <label className="field-label" htmlFor="product-name">Name<span aria-hidden="true" className="text-red-600 ml-0.5">*</span></label>
          <input
            id="product-name"
            type="text"
            required
            aria-required="true"
            className="field-input"
            placeholder="e.g. Braille Input Keypad"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          {!isEdit && (
            <p className="field-help">
              SKU will be generated from the name's initials plus a sequence number when you save.
            </p>
          )}
        </div>

        <div className="sm:col-span-2">
          <label className="field-label" htmlFor="product-desc">Description (optional)</label>
          <textarea
            id="product-desc"
            rows={3}
            className="field-input"
            placeholder="What it is, what's in the kit, who it's for…"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </div>

        <div className="sm:col-span-2">
          <label className="field-label" htmlFor="product-cat">Category (optional)</label>
          <input
            id="product-cat"
            type="text"
            className="field-input"
            placeholder="e.g. accessibility · filament · curriculum"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          />
        </div>

        <div className="sm:col-span-2">
          <label className="field-label">Type</label>
          <div className="flex gap-3">
            <label className={`flex-1 cursor-pointer card p-3 ${isDurable ? 'ring-2 ring-teal-500' : ''}`}>
              <input
                type="radio"
                name="type"
                checked={isDurable}
                onChange={() => setIsDurable(true)}
                className="mr-2"
              />
              <span className="font-medium">Durable</span>
              <p className="text-xs text-gray-500 mt-1">
                Tracked per unit with a serial number (robots, kits, devices).
              </p>
            </label>
            <label className={`flex-1 cursor-pointer card p-3 ${!isDurable ? 'ring-2 ring-amber-500' : ''}`}>
              <input
                type="radio"
                name="type"
                checked={!isDurable}
                onChange={() => setIsDurable(false)}
                className="mr-2"
              />
              <span className="font-medium">Consumable</span>
              <p className="text-xs text-gray-500 mt-1">
                Tracked by count on hand (filament, lesson packs, batteries).
              </p>
            </label>
          </div>
        </div>

        <div className="sm:col-span-2">
          <label className="flex items-center gap-2 text-sm text-gray-700">
            <input
              type="checkbox"
              checked={isActive}
              onChange={(e) => setIsActive(e.target.checked)}
            />
            Active (visible in school order forms and admin distribution)
          </label>
        </div>

        {err && (
          <div role="alert" className="sm:col-span-2 text-sm text-red-700 bg-red-50 border border-red-200 rounded-md px-3 py-2">
            {err}
          </div>
        )}

        <div className="sm:col-span-2 flex justify-end gap-2 pt-2 border-t border-warm-200">
          <button type="button" onClick={onClose} className="btn-secondary">Cancel</button>
          <button type="submit" className="btn-primary" disabled={saving || !name.trim()}>
            {saving ? 'Saving…' : (isEdit ? 'Save changes' : 'Create product')}
          </button>
        </div>
      </form>
    </div>
  );
}
